export const FOOD_CATEGORIES = [
  'Asian Fusion',
  'Bagels',
  'Bakery',
  'Bar',
  'Barbeque',
  'Breakfast',
  'British',
  'Brunch',
  'Buffets',
  'Burgers',
  'Cajun/Creole',
  'Caribbean',
  'Coffee/Espresso',
  'Country Food',
  'Cuban',
  'Deli',
  'Doughnuts',
  'Family Fare',
  'Fast Food',
  'Fine Dining',
  'Food Trucks',
  'French',
  'German',
  'Gluten-free',
  'Greek',
  'Happy Hour',
  'Hot Dogs',
  'Ice Cream',
  'Indian',
  'Irish',
  'Italian',
  'Japanese',
  'Latin American',
  'Live Entertainment',
  'Mediterranean',
  'Mexican',
  'Nouvelle',
  'Pancakes/Waffles',
  'Pizza',
  'Polish',
  'Sandwiches',
  'Seafood',
  'Soul Food',
  'Soup & Salad',
  'Southern',
  'Spanish',
  'Sports Bar',
  'Steaks',
  'Sushi',
  'Tapas',
  'Thai',
  'Vegan Friendly',
  'Vegetarian',
];

export const SHOPPING_CATEGORIES = [
  'Antiques',
  'Art Galleries',
  'Arts & Crafts',
  'Auction Houses',
  'Baby Gear',
  'Battery Stores',
  'Bespoke Clothing',
  'Books, Mags, Music & Video',
  'Brewing Supplies',
  'Bridal',
  'Cannabis Dispensaries',
  'Clothing',
  'Computers',
  'Cosmetics & Beauty Supply',
  'Customized Merchandise',
  'Department Stores',
  'Discount Stores',
  'Drones',
  'Drugstores',
  'Duty-Free Shops',
  'Electronics',
  'Eyeware & Opticians',
  'Farming Equipment',
  'Fashion',
  'Fireworks',
  'Fitness/Exercise Equipment',
  'Flea Markets',
  'Flowers & Gifts',
  'Gemstones & Minerals',
  'Gold Buyers',
  'Groceries',
  'Guns & Ammo',
  'Head Shops',
  'High Fidelity Audio Equipment',
  'Hobby Shops',
  'Home & Garden',
  'Horse Equipment Shops',
  'Jewelry',
  'Knitting Supplies',
  'Livestock Feed & Supply',
  'Luggage',
  'Medical Supplies',
  'Military Surplus',
  'Mobile Phone Accessories',
  'Mobile Phones',
  'Motorcycle Gear',
  'Musical Instruments & Teachers',
  'Office Equipment',
  'Outlet Stores',
  'Packing Supplies',
  'Pawn Shops',
  'Perfume',
  'Photography Stores & Services',
  'Pool & Billiards',
  'Pop-up Shops',
  'Props',
  'Public Markets',
  'Religious Items',
  'Safe Stores',
  'Safety Equipment',
  'Shopping Centers',
  'Souvenir Shops',
  'Spiritual Shops',
  'Sporting Goods',
  'Tabletop Games',
  'Teacher Supplies',
  'Thrift Stores',
  'Tobacco Shops',
  'Toy Stores',
  'Trophy Shops',
  'Uniforms',
  'Used Bookstore',
  'Vape Shops',
  'Vitamins & Supplements',
  'Watches',
  'Wholesale Stores',
  'Wigs',
];

export const EVENT_CATEGORIES = [
  'Film',
  'Arts & Theatre',
  'Music',
  'Sports',
  'Miscellaneous',
  'Nonticket',
];

export const BANNED_YELP_IDS = [
  'a4LjewExxqm72UJC1-Ct_Q',
  'C_AO6re_izyQrv9FTt0CcQ',
  'Z3EPvIqhUIaDHSgrVBNEAg',
];
