import { Business } from './business';

export class InfoObject {
  qr_code_link: string;
  id: string;
  type_of_info_object_category: number;
  is_community_member: string;
  type_of_info_object: string;
  image_url: string;
  hours: Array<any>;
  isOpenNow: any;
  location: any;
  categories: any;
  cleanCategories?: string;
  address: string;
  name: string;
  rating_image: string;
  rating: number;
  photo: string;
  alias: string;
  coordinates: any;
  _embedded: any;
  priceRanges: Array<any>;
  user_type: number;
  price: number = null;
  phone: string = null;
  distance = null;
  friendly_transactions = null;
  price_on = null;
  loc_x = null;
  loc_y = null;
  description: string = null;
  dates: any;
  review_count: string;
  loyalty_point_dollar_percent_value: string;
  photos: [];
  balance: string;
  rewardRate: string;
  display_phone: string;
  business: Business;
  url: string;
}
